export const authConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGIN_FAILURE'
}

export const userConstants = {
  USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
  USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',
  USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS'
}

export const categoryConstants = {
  GET_ALL_CATEGORIES_REQUEST: 'GET_ALL_CATEGORIES_REQUEST',
  GET_ALL_CATEGORIES_FAILURE: 'GET_ALL_CATEGORIES_FAILURE',
  GET_ALL_CATEGORIES_SUCCESS: 'GET_ALL_CATEGORIES_SUCCESS',
  ADD_NEW_CATEGORIES_REQUEST: 'ADD_NEW_CATEGORIES_REQUEST',
  ADD_NEW_CATEGORIES_FAILURE: 'ADD_NEW_CATEGORIES_FAILURE',
  ADD_NEW_CATEGORIES_SUCCESS: 'ADDS_NEW_CATEGORIES_SUCCESS'
}

export const productConstants = {
  GET_ALL_PRODUCTS_REQUEST: 'GET_ALL_PRODUCTS_REQUEST',
  GET_ALL_PRODUCTS_FAILURE: 'GET_ALL_PRODUCTS_FAILURE',
  GET_ALL_PRODUCTS_SUCCESS: 'GET_ALL_PRODUCTS_SUCCESS',
  ADD_NEW_PRODUCT_REQUEST: 'ADD_NEW_PRODUCT_REQUEST',
  ADD_NEW_PRODUCT_FAILURE: 'ADD_NEW_PRODUCT_FAILURE',
  ADD_NEW_PRODUCT_SUCCESS: 'ADD_NEW_PRODUCT_SUCCESS',
  GET_PRODUCTS_BY_SLUG: 'GET_PRODUCTS_BY_SLUG'
}
export const initialDataConstants = {
  GET_ALL_INITIAL_DATA_REQUEST: 'GET_ALL_INITIAL_DATA_REQUEST',
  GET_ALL_INITIAL_DATA_SUCCESS: 'GET_ALL_INITIAL_DATA_SUCCESS',
  GET_ALL_INITIAL_DATA_FAILURE: 'GET_ALL_INITIAL_DATA_FAILURE'
}



